### ISSUE TITLE
Doesn't play well with older version of http-party/node-http-proxy

### ISSUE THREAD

**Issue by geekdada** [vercel/node-file-trace#127]
node-file-trace can't trace modules inside the folder by using this [pattern](https://github.com/http-party/node-http-proxy/blob/1.15.0/lib/http-proxy.js#L4).

**Comment by styfle** [comment]
Thanks for reporting!

It looks like the bug is caused when a file and a folder share the same name, in this case:

- [lib/http-proxy.js](https://github.com/http-party/node-http-proxy/blob/1.15.0/lib/http-proxy.js)
- [lib/http-proxy/](https://github.com/http-party/node-http-proxy/tree/1.15.0/lib/http-proxy)

**Comment by geekdada** [comment]
Yes, but they are valid format https://nodejs.org/dist/latest-v14.x/docs/api/modules.html#modules_all_together

**Comment by lukebennett** [comment]
This issue is currently blocking me from deploying a service to Vercel - any idea of how long it's likely to be until this fix trickles down to @vercel/node?

**Comment by styfle** [comment]
I created a PR for `@vercel/node` here: https://github.com/vercel/vercel/pull/4814

Once that PR is merged, we'll release canary soon after.

Then it will be available sometime in the coming weeks in the next stable release.
